apiVersion: v1
kind: Service
metadata:
  name: sni-router-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sni-router
  ports:
  - name: sni-router-port
    protocol: TCP
    targetPort: sni-router-port
    port: 8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sni-router
  labels:
    app.kubernetes.io/name: sni-router
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sni-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sni-router
    spec:
      containers:
      - name: sni-router
        image: sni-test-registry:5000/traefik-sni:latest
        ports:
        - containerPort: 8888
          name: sni-router-port
