tcp:
  services:
    echo-0:
      loadBalancer:
        servers:
        - address: "echo-0.echo-svc.echo.svc.cluster.local.:8888"
    echo-1:
      loadBalancer:
        servers:
        - address: "echo-1.echo-svc.echo.svc.cluster.local.:8888"
    redpanda-0-kafka:
      loadBalancer:
        servers:
        - address: "redpanda-0.redpanda.redpanda.svc.cluster.local.:9063"
    redpanda-1-kafka:
      loadBalancer:
        servers:
        - address: "redpanda-1.redpanda.redpanda.svc.cluster.local.:9063"
    redpanda-2-kafka:
      loadBalancer:
        servers:
        - address: "redpanda-2.redpanda.redpanda.svc.cluster.local.:9063"
  routers:
    echo-0:
      entryPoints:
      - "echo"
      rule: "HostSNI(`echo-0.echo-svc.echo.svc.cluster.local`)"
      service: "echo-0"
      tls:
        passthrough: true
    echo-1:
      entryPoints:
      - "echo"
      rule: "HostSNI(`echo-1.echo-svc.echo.svc.cluster.local`)"
      service: "echo-1"
      tls:
        passthrough: true
    redpanda-0:
      entryPoints:
      - "rp-kafka"
      rule: "HostSNI(`redpanda-0.redpanda.redpanda.svc.cluster.local`)"
      service: "redpanda-0-kafka"
      tls:
        passthrough: true
    redpanda-1:
      entryPoints:
      - "rp-kafka"
      rule: "HostSNI(`redpanda-1.redpanda.redpanda.svc.cluster.local`)"
      service: "redpanda-1-kafka"
      tls:
        passthrough: true
    redpanda-2:
      entryPoints:
      - "rp-kafka"
      rule: "HostSNI(`redpanda-2.redpanda.redpanda.svc.cluster.local`)"
      service: "redpanda-2-kafka"
      tls:
        passthrough: true
