apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: v1
kind: Service
metadata:
  name: sni-router-svc
  namespace: traefik
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sni-router
  ports:
  - name: sni-router-port
    protocol: TCP
    targetPort: sni-router-port
    port: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: sni-router-external-svc
  namespace: traefik
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: sni-router
  externalTrafficPolicy: Cluster
  loadBalancerIP: 34.30.106.12
  ports:
  - name: external-echo
    protocol: TCP
    targetPort: traefik-echo
    port: 8888
  - name: external-rp-kafka
    protocol: TCP
    targetPort: traefik-kafka
    port: 9093

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sni-router
  namespace: traefik
  labels:
    app.kubernetes.io/name: sni-router
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sni-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sni-router
    spec:
      containers:
      - name: sni-router
        image: us-docker.pkg.dev/sandbox-customer-success/dv-docker-images/traefik-sni:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9093
          name: traefik-kafka
        - containerPort: 8888
          name: traefik-echo
