---
apiVersion: v1
kind: Service
metadata:
  name: traefik-lb
  namespace: traefik
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
  externalTrafficPolicy: Cluster
  # loadBalancerIP: 34.30.106.12
  ports:
  - name: external-echo
    protocol: TCP
    targetPort: echo
    port: 8888
  - name: external-rp-kafka
    protocol: TCP
    targetPort: rp-kafka
    port: 9094
  - name: external-rp-admin
    protocol: TCP
    taregetPort: rp-admin
    port: 9645
