---
apiVersion: v1
kind: Service
metadata:
  name: traefik-nodeports
  namespace: traefik
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: external-echo
      protocol: TCP
      targetPort: echo
      nodePort: 30888
      port: 8888
    - name: external-rp-kafka
      protocol: TCP
      targetPort: rp-kafka
      nodePort: 30094
      port: 9094
    - name: external-rp-admin
      protocol: TCP
      targetPort: rp-admin
      nodePort: 30645
      port: 9645
