apiVersion: v1
kind: Namespace
metadata:
  name: echo

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  namespace: echo
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: echo
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-cert
  namespace: echo
spec:
  dnsNames:
  - "*.echo-svc.echo.svc.cluster.local"
  - "*.echo-svc.echo.svc"
  - "*.echo-svc.echo"
  duration: 43800h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: default-cert
