apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: v1
kind: Service
metadata:
  name: sni-router-svc
  namespace: traefik
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sni-router
  ports:
  - name: sni-router-port
    protocol: TCP
    targetPort: sni-router-port
    port: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: sni-router-external-svc
  namespace: traefik
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sni-router
  ports:
  - name: external-echo
    protocol: TCP
    targetPort: traefik-echo
    nodePort: 30888
    port: 8888
  - name: external-rp-kafka
    protocol: TCP
    targetPort: traefik-kafka
    nodePort: 30094
    port: 9094
  - name: external-rp-admin
    protocol: TCP
    targetPort: traefik-admin
    nodePort: 30645
    port: 9645

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sni-router
  namespace: traefik
  labels:
    app.kubernetes.io/name: sni-router
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sni-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sni-router
    spec:
      containers:
      - name: sni-router
        image: sni-test-registry:5000/traefik-sni:latest
        ports:
        - containerPort: 8888
          name: traefik-echo
        - containerPort: 9094
          name: traefik-kafka
        - containerPort: 9645
          name: traefik-admin
